apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-application
  namespace: arindam
  labels:
    app: training-application
    role: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: training-application
  template:
    metadata:
      labels:
        app: training-application
    spec:
      containers:
        - name: training-application
          image: arimlregistry.azurecr.io/trainingapp:1.0.0 
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: 
            limits:
              cpu: 700m
              memory: 1Gi
            request: 
              cpu: 500m
              memory: 500mi
          env: 
            - name: ENV_VAR_1
              value: "Value defined in deployment object"
