apiVersion: v1
kind: Service
metadata:
  name: training-application
  namespace: arindam
  labels:
    app: training-application
spec:
  type: ClusterIP
  selector:
    app: training-application
  ports: 
    - name: http
      protocol: TCP
      port: 80
      targetPort: http